theme = "catppuccin_mocha"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
auto-format = false
color-modes = true
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.indent-guides]
render = true
character =  "┊"
skip-levels = 1

[editor.smart-tab]
enable = true

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

# create a new minor mode bound to `+`
[keys.normal."+"]
s = ":run-shell-command scons"
