theme = "catpuccin_mocha"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.insert.j]
k = "normal_mode" # emulate jk to esc just like in vim

[editor]
line-number = "relative"
color-modes = true # display's different colors for different modes
true-color = true
undercurl = true
text-width = 120 # max character limit to soft-wrap text
shell = ["cmd", '-c'] # default shell
scroll-lines = 5
insert-final-newline = false

[editor.indent-guides]
render = true
skip-levels = 0

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
"C-d" = ["half_page_down", "goto_window_center"]
"C-u" = ["half_page_up", "goto_window_center"]
# muscle memeory from VIM
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
V = ["select_mode", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
# visual mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[editor.lsp]
display-inlay-hints = true

[editor.smart-tab]
enable = false

[editor.whitespace.characters]
space = "."
tab = "->"
